version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'rlittlesii'
    open-pull-requests-limit: 5

  - package-ecosystem: 'nuget'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: "tuesday"
      time: "14:00"
    commit-message:
      prefix: "update:"
    assignees:
      - 'rlittlesii'
    ignore:
      - dependency-name: Microsoft.Extensions.*
      - dependency-name: Microsoft.AspNetCore.*
    open-pull-requests-limit: 5
