version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - 'rlittlesii'
    open-pull-requests-limit: 100

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - 'rlittlesii'
    open-pull-requests-limit: 100

  - package-ecosystem: 'nuget'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - 'rlittlesii'
    ignore:
      - dependency-name: Microsoft.Extensions.*
      - dependency-name: Microsoft.AspNetCore.*
    open-pull-requests-limit: 100
