version: 2
updates:

  - package-ecosystem: 'nuget'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: "tuesday"
      time: "14:00"
    commit-message:
      prefix: "update:"
    assignees:
      - 'rlittlesii'
    ignore:
      - dependency-name: Microsoft.Extensions.*
    open-pull-requests-limit: 10
