codecov:
    require_ci_to_pass: no
    bot: rsg-bot
    strict_yaml_branch: master

coverage:
    round: down
    precision: 2

    status:
        project: yes
        patch: yes
        changes: no

ignore:
  - "test/"  # ignore folders and all its contents        

comment:
    branch: master
