trigger:
  branches:
    include:
      - master
      - next
      - feature/*
      - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
      - master
      - next

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.13.0
      endpoint: github

variables:
  - group: rsg-bot
  - name: CONFIGURATION
    value: Release
  - name: VERBOSITY
    value: Normal
  - name: COVERAGE
    value: "$(Agent.BuildDirectory)/c"
  - name: ARTIFACTS
    value: $(Build.ArtifactStagingDirectory)
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: "true"
  - name: CodeCovToken
    value: 'ef5682ba-f998-4b0e-8a9e-2d9711c52f38'

jobs:
  - template: jobs/publish-release.yml@rsg
    parameters:
      GitHubPackages: true
      GitHubAuthVariableGroup: rsg-bot
      PublishNuGetPackagesFromArtifact: 'NuGet - macOS'

  - job: Build
    
    variables:
      - group: rsg-bot

    strategy:
      matrix:
        macOS:
          BuildName: 'macOS'
          ImageName: 'macOS-latest'

    pool:
      vmImage: $(ImageName)

    steps:
      - template: support/mono.yml@rsg

      - template: support/install-dotnet.yml@rsg
        parameters:
          DotNetSdk:
            - '2.x'
            - '3.x'
          AuthNuGetFeeds:
            - name: RocketSurgeonsGuild
              source: https://nuget.pkg.github.com/RocketSurgeonsGuild/index.json
              username: $(GitHub.UserName)
              password: $(GitHub.Token)

      - task: DotNetCoreCLI@2
        displayName: 'dotnet tool restore'
        inputs:
          command: custom
          custom: tool
          arguments: 'restore'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet restore'
        inputs:
          command: restore
          feedsToUse: config
          nugetConfigPath: NuGet.config
          verbosityRestore: Minimal

      - bash: ./build.sh --configuration '$(Configuration)' --target-platform $(Target_Platform) --artifacts '$(Artifacts)' --verbosity '$(Verbosity)'
        displayName: '⚙ Build'

      - template: support/publish-artifacts.yml@rsg
        parameters:
          Artifacts: $(Artifacts)
          Configuration: $(Configuration)
          Coverage: $(Coverage)
          Postfix: ' - $(BuildName)'
          PublishVSTest: true