<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <AssemblyName>Rocket.Surgery.Airframe.Analyzers</AssemblyName>
        <RootNamespace>Rocket.Surgery.Airframe.Analyzers</RootNamespace>
        <Description>Common analyzers for MVVM, MVU, Rx, and Airframe coding standards.</Description>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <GeneratedFolder>Generated</GeneratedFolder>
        <IsRoslynComponent>true</IsRoslynComponent>
        <IsPackable>false</IsPackable>
        <NoWarn>RS1022</NoWarn>
        <NoPackageAnalysis>true</NoPackageAnalysis>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all"/>
    </ItemGroup>
    <ItemGroup>
        <None Include=".\AnalyzerReleases.Shipped.md" Pack="true" PackagePath="\"/>
    </ItemGroup>
    <ItemGroup>
        <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="$(AssemblyName).Tests"/>
        <InternalsVisibleTo Include="Rocket.Surgery.Airframe.CodeFixes"/>
        <InternalsVisibleTo Include="Rocket.Surgery.Airframe.CodeFixes.Tests"/>
    </ItemGroup>
</Project>
