#!/usr/bin/env bash
# Automatically adds branch prefix to the beginning of the first commit message.

# Get the current branch name
BRANCH=$(git symbolic-ref --short HEAD)
echo "Current Branch: $BRANCH"

# Extract the prefix from the branch name
BRANCH_PREFIX=$(echo "$BRANCH" | cut -d'/' -f1)
echo "Branch Prefix: $BRANCH_PREFIX"

# Define acceptable prefixes for commit messages
acceptable_prefixes=("feature" "screen" "fix" "ci" "chore" "docs" "test" "style" "enhancement")

# Get the first commit message
FIRST_COMMIT=$(git log --format=%B --reverse main.."$BRANCH" | head -n 1)
echo "First Commit: $FIRST_COMMIT"

# Check if the first commit message already has an acceptable prefix
has_acceptable_prefix=false
for prefix in "${acceptable_prefixes[@]}"; do
  if [[ "$FIRST_COMMIT" == "$prefix"* ]]; then
    has_acceptable_prefix=true
    break
  fi
done

if ! $has_acceptable_prefix; then
  # Add the branch prefix as the first line of the commit message
  sed -i.bak "1s/^/$BRANCH_PREFIX: /" "$1"
  rm "$1.bak"
fi