#!/usr/bin/env bash
# Automatically adds branch prefix to the beginning of the first commit message.

# Get the current branch name
BRANCH=$(git symbolic-ref --short HEAD)
echo "Current Branch: $BRANCH"

# Define acceptable prefixes for commit messages
acceptable_prefixes=("feature" "screen" "fix" "ci" "chore" "docs" "test" "style" "enhancement")

# Extract the correct prefix from the branch name
BRANCH_PREFIX=""
IFS='/' read -ra PARTS <<< "$BRANCH"
for part in "${PARTS[@]}"; do
  if [[ " ${acceptable_prefixes[*]} " == *" $part "* ]]; then
    BRANCH_PREFIX=$part
    break
  fi
done

# Fallback if no known prefix is found
if [[ -z "$BRANCH_PREFIX" ]]; then
  BRANCH_PREFIX="${PARTS[0]}"
fi

echo "Branch Prefix: $BRANCH_PREFIX"

# Get the first commit message
FIRST_COMMIT=$(git log --format=%B --reverse main.."$BRANCH" | head -n 1)
echo "First Commit: $FIRST_COMMIT"

# Check if the first commit message already has an acceptable prefix
has_acceptable_prefix=false
for prefix in "${acceptable_prefixes[@]}"; do
  if [[ "$FIRST_COMMIT" == "$prefix"* ]]; then
    has_acceptable_prefix=true
    break
  fi
done

# Modify commit message if needed
if ! $has_acceptable_prefix; then
  sed -i.bak "1s/^/$BRANCH_PREFIX: /" "$1"
  rm "$1.bak"
fi