name: Sync Labels
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/sync-labels.yml
      - .github/labels.yml
  schedule:
    - cron: '0 0 * * 4'

jobs:
  sync_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.3.0

      - name: Checkout tools repo
        uses: actions/checkout@v4.3.0
        with:
          repository: RocketSurgeonsGuild/.github
          path: .rsg

      - name: merge files
        uses: RocketSurgeonsGuild/actions/merge-labels@v0.3.15
        with:
          files: '.rsg/.github/labels.yml,.github/labels.yml'
          output: .github/labels.yml

      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v5.3.0
        with:
          yaml_file: .github/labels.yml
          skip_delete: false
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
