name: Update Milestone
on:
  pull_request:
    types:
      - closed
      - opened
      - reopened
      - synchronize

jobs:
  update_milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: sync milestones
        uses: RocketSurgeonsGuild/actions/sync-milestone@v0.3.2
        with:
          default-label: ':sparkles: mysterious'
          github-token: ${{ secrets.GITHUB_TOKEN }}
